# Generated by Django 6.1 on 2026-09-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_populate_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=255)),
                ('courses', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=50)),
                ('study_program', models.CharField(max_length=255)),
                ('bio_intro', models.TextField()),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('organizations_count', models.PositiveIntegerField(default=0)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('competitions', models.JSONField(blank=True, default=list)),
                ('photo', models.URLField(blank=True)),
                ('cv_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gallery', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
