# Generated by Django 4.2.30 on 2026-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_populate_portfolio_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='', max_length=255),
        ),
    ]
