# Generated by Django 4.2.30 on 2026-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_project_starred_by_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Rayyouw', max_length=50),
            preserve_default=False,
        ),
    ]
