# Generated by Django 4.2.30 on 2026-09-30 07:49

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='rayyouw').exists():
        User.objects.create(
            username='rayyouw',
            password=make_password('ray123'),
            is_superuser=True,
            is_staff=True
        )
    else:
        u = User.objects.get(username='rayyouw')
        u.password = make_password('ray123')
        u.is_superuser = True
        u.is_staff = True
        u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_certificate'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
