# Generated by Django 4.2.30 on 2026-09-30 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
